# Generated by Django 4.2.1 on 2023-05-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(default='undecided', max_length=255, unique=True),
        ),
    ]
