# Generated by Django 4.2 on 2023-05-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_categories_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='slug',
            field=models.SlugField(default='undecided', max_length=100, unique=True),
        ),
    ]
