# Generated by Django 4.2 on 2023-05-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listings_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='slug',
        ),
    ]
