# Generated by Django 4.2 on 2023-05-09 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_listings_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initialBids', models.DecimalField(decimal_places=2, max_digits=1000)),
            ],
            options={
                'ordering': ['initialBids'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='undecided')),
                ('date', models.DateField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.RemoveField(
            model_name='listings',
            name='category',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('LA', 'LiveAuction'), ('OA', 'OnlineAuction'), ('SBA', 'SealedBidAuction')], default=('LA', 'LiveAuction'), max_length=255),
        ),
        migrations.AlterField(
            model_name='listings',
            name='initialBids',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.bids'),
        ),
    ]
