# Generated by Django 4.2 on 2023-05-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listings_initialbids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='initialBids',
            field=models.DecimalField(decimal_places=2, max_digits=1000000),
        ),
    ]
