# Generated by Django 4.2 on 2023-05-09 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_delete_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='example@gmail.com', max_length=255, unique=True),
        ),
    ]
