# Generated by Django 4.2 on 2023-05-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_listings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='user',
            field=models.CharField(default='undecided', max_length=255, unique=True),
        ),
    ]
