# Generated by Django 4.2 on 2023-05-15 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_alter_comments_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingUser', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
