# Generated by Django 4.2 on 2023-05-15 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_alter_listings_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='date',
        ),
    ]
