# Generated by Django 4.2.1 on 2023-05-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_remove_comments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.ImageField(upload_to='C:\\Users\\User\\Downloads\\projects\\commerce/images'),
        ),
    ]
